language: julia
dist: trusty
sudo: true
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("CDCL")'
  - julia -e 'Pkg.test("CDCL", coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("CDCL")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("CDCL")); include(joinpath("docs", "make.jl"))'
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
